export enum ActionTypes {
	SEARCH_ERROR = 'SEARCH_ERROR',
	SEARCH_PENDING = 'SEARCH_PENDING',
	SEARCH_SUCCESS = 'SEARCH_SUCCESS',
	SELECT_OPTION = 'SELECT_OPTION',
	SET_INPUT = 'SET_INPUT',
	SET_CREWS = 'SET_CREWS',
	SELECT_CREW = 'SELECT_CREW',
	SET_ORDER_INFO = 'SET_ORDER_INFO',
}
